# Generated by Django 5.1 on 2024-10-06 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalAPI', '0003_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('IV', 'Категория IV'), ('VI', 'Категория VI'), ('I', 'Категория I'), ('III', 'Категория III'), ('II', 'Категория II'), ('V', 'Категория V')], default='I', max_length=3, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('IV', 'Категория IV'), ('VI', 'Категория VI'), ('I', 'Категория I'), ('III', 'Категория III'), ('II', 'Категория II'), ('V', 'Категория V')], default='I', max_length=3, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('IV', 'Категория IV'), ('VI', 'Категория VI'), ('I', 'Категория I'), ('III', 'Категория III'), ('II', 'Категория II'), ('V', 'Категория V')], default='I', max_length=3, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('IV', 'Категория IV'), ('VI', 'Категория VI'), ('I', 'Категория I'), ('III', 'Категория III'), ('II', 'Категория II'), ('V', 'Категория V')], default='I', max_length=3, verbose_name='Зима'),
        ),
        migrations.CreateModel(
            name='SpecificationOfPereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('other_titles', models.CharField(blank=True, max_length=128)),
                ('connect', models.CharField(blank=True, max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новое описание'), ('pnd', 'На рассмотрении'), ('acp', 'Подтверждено'), ('rjt', 'Отклонено')], default='new', max_length=3)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perevalAPI.coordinates')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalAPI.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
