# Generated by Django 5.1 on 2024-10-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalAPI', '0004_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('V', 'Категория V'), ('III', 'Категория III'), ('I', 'Категория I'), ('VI', 'Категория VI'), ('II', 'Категория II'), ('IV', 'Категория IV')], default='I', max_length=3, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('V', 'Категория V'), ('III', 'Категория III'), ('I', 'Категория I'), ('VI', 'Категория VI'), ('II', 'Категория II'), ('IV', 'Категория IV')], default='I', max_length=3, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('V', 'Категория V'), ('III', 'Категория III'), ('I', 'Категория I'), ('VI', 'Категория VI'), ('II', 'Категория II'), ('IV', 'Категория IV')], default='I', max_length=3, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('V', 'Категория V'), ('III', 'Категория III'), ('I', 'Категория I'), ('VI', 'Категория VI'), ('II', 'Категория II'), ('IV', 'Категория IV')], default='I', max_length=3, verbose_name='Зима'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField(max_length=1500, verbose_name='Cсылка на вид')),
                ('title', models.TextField(verbose_name='Описание вида')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='perevalAPI.specificationofpereval', verbose_name='Вид перевала')),
            ],
        ),
    ]
